### PR TITLE
Fixed wrong answer on object instances comparison

### PR DESCRIPTION
**Pull request by lolautruche**
`instanceof` only checks the class of a variable. It doesn't allow object comparison.
`===` must be used here (`==` is not sufficient as it doesn't check the type).

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi Jérome,

thanks again, this repository definetively need some love (I've added a lot of questions to bootstrap the repository but I don't use it).

Let me know if you want more rights on PHP and Symfony decks :)

**Comment by lolautruche** [comment]
Thanks for merging! 
I won't be able to open more PRs on the Symfony deck as I've just had the certification exam... However I can still fix the php pack :smiley:

**Comment by mickaelandrieu** [comment]
Congrats for your certification :)

**Comment by lolautruche** [comment]
Thanks 🎉

**Pull request merged**
