### PR TITLE
Update strings-patterns.yml

### PR DESCRIPTION
**Pull request by l-vo**
Several answers are right

### CODE REVIEW

**Comment by lex111** [comment]
Hi @l-vo 

I checked the two regular expressions at https://regex101.com/, and it did not give a complete match, so now everything is correct and there is no need to fix anything.

**Comment by l-vo** [comment]
So maybe it is the question that is not precise enough. A preg_match of the patterns `[hp1-5]*\-.?`or `[a-z1-5\-]*` will return true on the string `PhP5-rocks`. Therefore these two patterns matches too. The question don't talk about a complete or not match.

What do you think of changing the question by (pushed on the branch of the PR):
> Which PCRE regular expression will match the totality of the string PhP5-rocks

**Comment by lex111** [comment]
Maybe a little bit differently?

> Which PCRE regular expression will match exactly the string PhP5-rocks

**Comment by l-vo** [comment]
Question updated :)

**Review by lex111 — APPROVED** [review]

**Comment by lex111** [comment]
@l-vo awesome, thanks!

**Pull request merged**
